<?php
    // Include FPDF library
    require 'php.report/fpdf/fpdf.php';
    require 'php.report/reports-utils.php';
    include 'php.utils/activity-logging.php';

    global $curID;
    $curID = $_SESSION['currentUserID'];

    if(isset($_POST['genrep'])){
        $min = $_POST['start'];
        $max = $_POST['end'];

        $username = Fetch_Username();

        // LogActivity_GenerateReport($curID);
        GenerateReport($username, $min, $max);
    }

    // Generate a PDF Report
    function GenerateReport($username, $min, $max){
        global $conn;

        // Misc
        $generatedDate = date('m-d-Y');

        // FPDF Initialization (acting as procedural steps)
        
        // Title
        // Table Header
        // Extend the FPDF class
        class PDF extends FPDF {
            // Custom Header method
            function Header() {
                // Set Image
                $this->Image('resource/application-icon.png', 3, 3, -900);
                // Set font for the header
                $this->SetFont('Arial', 'B', 18);
                $this->SetTextColor(46, 204, 64);
                // Add a title
                $this->Cell(0, 0, 'Habere System Report', 0, 1, 'C'); // Centered title
                $this->Line(0, 18, 300, 18); // X1, Y1, X2, Y2
                // Add a line break
                $this->Ln(10);
                // Draw a horizontal line
                // $this->Line(0, 20, 300, 20); // X1, Y1, X2, Y2
                $this->Ln(5); // Extra space after the line
            }
            function Footer()
            {
                // Go to 1.5 cm from bottom
                $this->SetY(-10);
                $this->SetFont('Arial', 'B', 12);   
                $this->Line(0, 200, 300, 200); // X1, Y1, X2, Y2
                $this->Cell(0, 10, "Generated with: Habere Admin System", 0, 'L');
            }
        }
        
        $pdf = new PDF(); // Create the PDF instance
        $pdf->SetTextColor(18, 32, 35);
        $pdf->AddPage('L');   // Add a page
        
        $pdf->SetFont('Arial', 'B', 12); // Set font
        $pdf->Cell(0, 5, "Generated by: $username",0,1);
        $pdf->Cell(0, 5, "Report Date: $generatedDate",0,1);
        $pdf->Line(0, 40, 300, 40); // X1, Y1, X2, Y2
        $pdf->Ln(10);
        
        // Palette
        /*
        --backgroundcolor:rgb(18, 32, 35);
        --primarycolor:rgb(46, 204, 64);
        --secondarycolor:rgb(255, 255, 255);
        --hyperlinks:rgb(0, 123, 255);
        */
        
        $dat = date('M, Y');

        // $start = date_create($min);
        // $end = date_create($max);


        // $diff = date_diff($start, $end);
        // $interval = $diff->format('%m Months');    

        $ts2 = strtotime($min);
        $ts1 = strtotime($max);

        $year1 = date('Y', $ts1);
        $year2 = date('Y', $ts2);

        $month1 = date('m', $ts1);
        $month2 = date('m', $ts2);

        $interval = (($year2 - $year1) * 12) + ($month2 - $month1);

        
        // NEW TABLE
        // USER RETENTION RATE
        if(!empty($_POST['retention'])){
            $pdf->SetFont('Arial', 'B', 12);
            $pdf->Cell(60, 6, "Users", 0, 1);
            $pdf->Cell(60, 6, "User Retention Over Time ($dat)", 0, 1);

            // Table Header
            $pdf->SetFillColor(46, 204, 64);
            $pdf->SetTextColor(255, 255, 255);
            $pdf->Cell(60, 6, "Date", 1, 0, '', true);
            $pdf->Cell(60, 6, "Registered Users", 1, 0, '', true);
            $pdf->Cell(60, 6, "Active Users", 1, 0, '', true);
            $pdf->Cell(60, 6, "Retention Rate", 1, 0, '', true);
            $pdf->Ln();
            
            
            $pdf->SetFont('Arial', '', 12);
            $pdf->SetTextColor(18, 32, 35);
            $mod = date_create($min);
            // Offset
            $mod = date_modify($mod, "+1 day");

            for ($i=0; $i <= $interval; $i++) { 
                $regUsers = Fetch_RegisteredUsersByMonth($mod);
                $actUsers = Fetch_ActiveUsersByMonth($mod);
                $rate = number_format(($actUsers != 0 ? $actUsers / $regUsers : 0)*100,0);
                
                // Draw data to rows
                $pdf->Cell(60, 6, date_format($mod, 'M, Y'), 1);
                // $pdf->Cell(60, 6, date('n') - $i, 1);
                $pdf->Cell(60, 6, $regUsers, 1);
                $pdf->Cell(60, 6, $actUsers < 0 ? 0 : $regUsers, 1);
                $pdf->Cell(60, 6, "$rate%", 1);
                $pdf->Ln();

                $mod = date_modify($mod, "-1 Months");
            }
            $pdf->Ln(10);
        }
        

        // NEW TABLE
        // COMPLETION OVER TIME
        if(!empty($_POST['habitTrends'])){
            $pdf->SetFont('Arial', 'B', 12);
            $pdf->Cell(60, 6, "Habit Trends", 0, 1);
            $pdf->Cell(60, 6, "Completion Over Time ($dat)", 0, 1);

            // Table Header
            $pdf->SetFillColor(46, 204, 64);
            $pdf->SetTextColor(255, 255, 255);
            $pdf->Cell(60, 6, "Date", 1, 0, '', true);
            $pdf->Cell(60, 6, "Tracked Habits", 1, 0, '', true);
            $pdf->Cell(60, 6, "Completed Habits", 1, 0, '', true);
            $pdf->Cell(60, 6, "Completion Rate", 1, 0, '', true);
            $pdf->Ln();
            
            
            $pdf->SetFont('Arial', '', 12);
            $pdf->SetTextColor(18, 32, 35);
            $mod = date_create($min);
            // Offset
            $mod = date_modify($mod, "+1 day");

            for ($i=0; $i <= $interval; $i++) { 
                $habits = Fetch_TotalsByMonth('habits',$mod);
                $comHabits = Fetch_TotalsByMonth('habit_logs',$mod);

                $rate = number_format(($comHabits != 0 ? $comHabits / $habits : 0)*100,0);
                
                // Draw data to rows
                $pdf->Cell(60, 6, date_format($mod, 'M, Y'), 1);
                $pdf->Cell(60, 6, $habits, 1);
                $pdf->Cell(60, 6, $comHabits < 0 ? 0 : $comHabits, 1);
                $pdf->Cell(60, 6, "$rate%", 1);
                $pdf->Ln();
                
                $mod = date_modify($mod, "-1 Months");
            }
            $pdf->Ln(10);
        }

        // $conn->close();
        // Output PDF
        $pdf->Output('I',"Habere System Report ($generatedDate)");
    }
?>